language:
  - cpp  
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - ./configure --enable-gcov && make && make check
after_success:
  - npm run coveralls
script:
  - qmake
  - make
  - ./tests/tests
  
