language:
  - cpp  
compiler:
  - gcc
before_install:
  - pip install --user cpp-coveralls
script:
  - ./configure --enable-gcov && make && make check
after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
script:
  - qmake
  - make
  - ./tests/tests
  
